[build]
  base = "reactapp" 
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "https://api.example.com"
  API_KEY = "your-secret-api-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200